### ISSUE TITLE
Optimize Conan Plugin for CLion to Improve Remote Development and Cross-Compilation Support

### ISSUE THREAD

**Issue by jelin-sh** [conan-io/conan-clion-plugin#157]
### Description:

1. I would like to see an optimization in the Conan plugin for CLion's remote development support. Specifically, I suggest changing the absolute paths in the CMake option `CMAKE_PROJECT_TOP_LEVEL_INCLUDES` to relative paths. I'm not sure why it was designed to use absolute paths, and I'm curious if changing it to relative paths would cause any issues. Currently, when using CLion's remote development feature, I have to disable the "Automatically add Conan support for all configurations" option and manually switch `CMAKE_PROJECT_TOP_LEVEL_INCLUDES` to relative paths.

2. I'm not clear on how to use the Conan plugin to configure cross-compilation for third-party dependencies. Could an example be provided?

### Use Case:

1. Remote Development
2. Cross-Platform

**Comment by czoido** [comment]
Hi @skjsnb, 

Thanks a lot for the feedback. Regarding the relative path for `CMAKE_PROJECT_TOP_LEVEL_INCLUDES` I think that's definitely something we can change, so I'm marking this issue for the 2.0.2 milestone and we will update that.

For the cross-compilation part, most of the job that Conan does in the plugin is directed by the conan_provider.cmake integration that we use: https://github.com/conan-io/cmake-conan/tree/develop2 so most of it depends on it and on how CLion does cross-building itself.
We can make some tests to check how this fits with the plugin and the provider because this has not been tested a lot yet.
