### ISSUE TITLE
Feature request: Add local packages to package list

### ISSUE THREAD

**Issue by Eric-Bwr** [conan-io/conan-clion-plugin#178]
I would like to be able to see my self build packages in the clion conan list aswell (just like for ex. 7zip and the other packages).
Maybe with a prefix like: local/name
Or a own list for that.
Thx in advance :)

**Comment by konradx64** [comment]
@czoido  i would love to have this feature, no answer for almost two months.

**Comment by czoido** [comment]
Hi @Eric-Bwr, @knimix 

Sorry for the delay in answering; I overlooked this.
Thank you very much for the feedback. The issue here is that we do not use Conan to retrieve the list of packages. The plugin is distributed [with a file](https://github.com/conan-io/conan-clion-plugin/blob/519f4e274259e522aabc78dae7fd2681aa4682a7/src/main/resources/conan/targets-data.json) that is updated daily with new changes from Conan Center and contains additional information. The primary intention of this plugin has always been to facilitate the most common beginner scenario: consuming third-party packages from Conan Center easily. For other use cases, such as when you would like to use your own packages, the best approach is to edit the `conandata.yml` file that the plugin generates.

**Comment by Eric-Bwr** [comment]
Alright, ill close this then. :/
