### ISSUE TITLE
Publishing a forked version

### ISSUE THREAD

**Issue by Lawrencemm** [conan-io/conan-clion-plugin#37]
Hello, I'm considering forking this with some experimental features and publishing it separately on the JetBrains repo for other people to try.

I'm asking if this is OK to do by you guys and legally as well.

**Comment by memsharded** [comment]
Hi @Lawrencemm 

Yes, it is under the MIT license, so it is perfectly fine to fork it and do your own modifications, you only need to comply with the license (attribution, you can typically add your copyright to the existing one, etc)

Regarding the Jetbrains repo, I cannot say, I don't know if they encourage to have single providers, or coming from the "official" teams, but you can ask and try, I am good with that.

However, I would consider to try to not diverge, unless there is really no other way because it is too breaking. It is typically bad for the community, which would be confused which one to use. Consider introducing them to the main Conan repo, maybe discuss with @jgsogo if it is possible some kind of switch "experimental" for these things. Or maybe, consider forking, but when things mature from your side, to submit them to the Conan repo, to make it "official", and do not diverge them too much over time. Also, if forking, merging the last updates from the Conan repo would be recommended too.

**Comment by Lawrencemm** [comment]
Thanks, that's all really helpful.
